[package]
name = "solana-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
solana-hash.workspace = true
solana-pubkey.workspace = true
solana-signature.workspace = true
thiserror.workspace = true

[dev-dependencies]
bs58.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
