[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dev-dependencies]
archive-format = { path = "../../crates/archive-format", version = "=0.1.0" }
archive-writer = { path = "../../services/archive-writer", version = "=0.1.0" }
observation-envelope = { path = "../../crates/observation-envelope", version = "=0.1.0" }
platform-proto = { path = "../../crates/platform-proto", version = "=0.1.0" }
prost.workspace = true
rdkafka.workspace = true
storage-adapters = { path = "../../crates/storage-adapters", version = "=0.1.0" }
storage-ports = { path = "../../crates/storage-ports", version = "=0.1.0" }
tempfile.workspace = true
test-fixtures = { path = "../../crates/test-fixtures", version = "=0.1.0" }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "time"] }
wal = { path = "../../crates/wal", version = "=0.1.0" }

[lints]
workspace = true
