[package]
name = "evm-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alloy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
test-fixtures = { path = "../test-fixtures", version = "=0.1.0" }

[lints]
workspace = true
