[package]
name = "evm-canonicality"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
evm-domain = { path = "../../crates/evm-domain", version = "=0.1.0" }
thiserror.workspace = true

[lints]
workspace = true
