redpanda:
  data_directory: /var/lib/redpanda/data
  node_id: 0
  seed_servers: []
  rpc_server:
    address: 0.0.0.0
    port: 33145
  advertised_rpc_api:
    address: redpanda
    port: 33145
  kafka_api:
    - name: local
      address: 0.0.0.0
      port: 19092
  advertised_kafka_api:
    - name: local
      address: 127.0.0.1
      port: 19092
  admin:
    - address: 0.0.0.0
      port: 19644
  developer_mode: true

rpk:
  overprovisioned: true
  tune_network: false
  tune_disk_scheduler: false
  tune_disk_nomerges: false
  tune_disk_irq: false
  tune_fstrim: false
  tune_cpu: false
  tune_aio_events: false
  tune_clocksource: false
  tune_swappiness: false
  coredump_dir: /var/lib/redpanda/coredump
